/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import java.util.ArrayList;

import com.tcs.tallerListas.beans.Estudiante;
import com.tcs.tallerListas.beans.Mensajes;
import com.tcs.tallerListas.beans.comparador;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Collections;

import java.util.Scanner;


public class IngresoEstudiantes {

    public static void main(String[] args) {
        int a = 0;
        int b = 0;
        int indice=0;
        final int seis=6;
        final int diez=10;
        int valonum=0;
        final String tipid="TI";
        final String cursar="SI";
        Mensajes msg = new Mensajes();
        ArrayList<Estudiante> vectorEstudiante = new ArrayList<Estudiante>();

        System.out.println(msg.mgshmenu);

        try {
            Scanner data = new Scanner(new File("src/main/resources/data.txt"));
            while (data.hasNextLine()) {
                // Aqui guardo la variable de la cantidad de alumos
                a += 1;
                String[] estData = data.nextLine().split(",");
                Estudiante dato1 = new Estudiante(estData[0],estData[1],estData[2],estData[3],estData[4]);
                vectorEstudiante.add(dato1);

            }
        } catch (FileNotFoundException e) {
            System.out.println(msg.mensajearch);
        }

        // a. Imprime los registros total de alumnos
        System.out.println(msg.nroestudiante + a);

        // b. Se busca la cantidad de alumnos entre 6 a 10 años.
        for (int e= 0;e<vectorEstudiante.size();e++) {

            Estudiante auxEstudiante = vectorEstudiante.get(e);

            String valor = auxEstudiante.getEdad();

            //Valido si es numerico
            if (isNumeric(valor)){
                  valonum = Integer.parseInt(valor);
            } else {
                System.out.println(msg.mensajeError);
            }

           if(valonum >= seis && valonum <= diez){
               b += 1;
            }
        }

        System.out.println(msg.separador);

        //b. Número de estudiantes entre los 6 y los 10 años de edad
        System.out.println(msg.msgnroest + b);

        System.out.println(msg.separador);


        //C. Separar los estudiantes en diferentes listas por grado e imprimir
        System.out.println(msg.msglista);
        Collections.sort(vectorEstudiante, new comparador());

        for (Estudiante p : vectorEstudiante) {
            System.out.println(msg.msgnom + p.getNombre() + " "+ msg.msggrd + p.getGrado());
        }

        System.out.println(msg.separador);

        // d. Se busca los registros de los estudiantes tenga empiezan por TI
        System.out.println(msg.msgestti);
        for (int e= 0;e<vectorEstudiante.size();e++) {

            Estudiante auxEstudiante1 = vectorEstudiante.get(e);
            String identidad = auxEstudiante1.getIdentificacion();

            if (tipid.equals(identidad.substring(0,2))){
                System.out.println(msg.msgid + auxEstudiante1.getIdentificacion() + msg.msgnom + auxEstudiante1.getNombre() + msg.msgedad + auxEstudiante1.getEdad() + msg.msggrd + auxEstudiante1.getGrado() );
            }
        }

        System.out.println(msg.separador);
        System.out.println(msg.msgrepite);

            // Estudiante que repiten el años
        for (int j= 0;j<vectorEstudiante.size();j++) {

                Estudiante auxEstudiante2 = vectorEstudiante.get(j);

                String repite = auxEstudiante2.getRepite().toUpperCase();

                if (cursar.equals(repite)) {
                    System.out.println(msg.msgnom + auxEstudiante2.getNombre());
                }

        }








    }

        public static boolean isNumeric(String value) {

            // implementa un bloque try catch aca
            try {
                Integer.parseInt(value);
                return true;
            } catch (NumberFormatException e) {
                return false;
            }

        }

}
